@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3ZDNkOTk1NGU1ZDliZTZiOTYxZjMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzI0NjI5OCwiZXhwIjoxNzQzMjUzNDk4fQ.cEYwF0nJ-td9BzjK6lU6U5J2OCHp-2wzV_SnG3vFFGU

### Registro de un nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "cristiano.ronaldo@email.com",
  "password": "ay-mi-m4dre-3l-b1ch8888"
}

### Verificación de correo electrónico (El usuario ingresa el código que recibió en su email)
POST http://localhost:3000/api/auth/verify-email
Content-Type: application/json
Authorization: {{authToken}}

{
  "email": "cristiano.ronaldo@email.com",
  "verificationCode": "374825"
}

### Login después de verificación del correo (El usuario tiene que estar verificado)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "cristiano.ronaldo@email.com",
  "password": "ay-mi-m4dre-3l-b1ch8888"
}

### Actualización de datos del usuario
PUT http://localhost:3000/api/auth/67e7dc5539bdf94faad742b0
Content-Type: application/json
Authorization: {{authToken}}

{
  "email": "cr7@gmail.com",
  "password": "ay-mi-m4dre-3l-b1ch0000",
  "name": "Cristiano",
  "lastname": "Ronaldo",
  "nif": "12345678Z"
}