@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U1YzgyNjI3OTM3ZDNkNzMxYjgxYzAiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzExMjIzMCwiZXhwIjoxNzQzMTE5NDMwfQ.r_xwCZ_eoq__28AaATL-s71szMMcS1lWimYok9vKSg4

### Registro de un nuevo usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "juan.perez@email.com",
  "password": "contraseña-segura"
}

### Verificación de correo electrónico (El usuario ingresa el código que recibió en su email)
POST http://localhost:3000/api/auth/verify-email
Content-Type: application/json
Authorization: {{authToken}}

{
  "email": "juan.perez@email.com",
  "verificationCode": "496760"
}

### Login después de verificación del correo (El usuario tiene que estar verificado)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "juan.perez@email.com",
  "password": "contraseña-segura"
}
